name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    # Released in April 2024
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: alsa
      # https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
